### ISSUE TITLE
Design Free ATS and Features Section

### ISSUE THREAD

**Issue by doesnots** [tcet-opensource/resume-screener-frontend#6]
# Create the ATS resume test section 
Keep the buttons clickable and try to make it responsive.
![image](https://github.com/tcet-opensource/resume-screener-frontend/assets/59131714/9a4ad306-d52f-4449-942b-5e3f9d08835c)

**Design mobile-first** 

# Follow folder structure:
public -> ATSResumeTest -> _assets here_
components -> ATSResumeTest -> _components here_ 

# Fonts
Inter is the default font
Rubik is the title font - use classname `font-rubik`
Fonts are already linked and setup is done for everything.

**Comment by yashodharpatel** [comment]
@doesnots What needs to be done when button is clicked ? An it is just like a UI na i neeed to create it using the text shown in image anything else is to be done ?

**Comment by doesnots** [comment]
@yashodharpatel As for now the button must be just clickable,
You can leave the link empty.
Just try to make the frontend as close as possible to figma file.
